### ISSUE TITLE
What is the ffmpeg command you used for your airpods demo?

### ISSUE THREAD

**Issue by mattpilott** [lqez/lqez.github.io#1]
Hey,

Came across your airpods demo today looking for answers to high memory usage when creating an image sequence like the apple airpods page

Maybe a video is a better solution!

Would you be so kind as to let me know what the command is to convert image frames to video?

Thanks,
Matt

**Comment by lqez** [comment]
Hi @matt3224!
Thank you for stopping by.

I'm not sure the exact value, but it would have been created by `libx264` codec with `-intra` option.
e.g.) `ffmpeg -framerate 30 -pattern_type glob -i '*.png'  -c:v libx264 -crf 30 -intra -pix_fmt yuv420p out.mp4`

**Comment by mattpilott** [comment]
@lqez perfect thanks for taking the time to get that to me
